# Generated by Django 3.1.5 on 2021-01-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
